### ISSUE TITLE
Several errors when running the newest version

### ISSUE THREAD

**Issue by clam2310** [pwc-technology-be/eu-captcha#83]
I downloaded the newest master, created a WAR file and deployed it to a Tomcat 8 server.
The test page is loaded fine and I can see the image. Changing the language also reloads the image. But neither "Reload" nor "Submit" work as they return 403 responses.

Unfortunately your controller actions do not log any errors and turns all exceptions into ForbiddenExceptions. I added some logging and found two exceptions that are thrown:

```
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source)
	at com.sii.eucaptcha.captcha.text.textProducer.impl.DefaultTextProducer.getRandomSetElement(DefaultTextProducer.java:31)
	at com.sii.eucaptcha.captcha.text.textProducer.impl.DefaultTextProducer.getText(DefaultTextProducer.java:25)
	at com.sii.eucaptcha.captcha.Captcha$CaptchaBuilder.withText(Captcha.java:77)
	at com.sii.eucaptcha.service.CaptchaService.generateCaptchaImage(CaptchaService.java:152)
```

and

```
java.lang.IllegalArgumentException: signing key cannot be null.
	at io.jsonwebtoken.lang.Assert.notNull(Assert.java:82)
	at io.jsonwebtoken.impl.DefaultJwtParserBuilder.setSigningKey(DefaultJwtParserBuilder.java:165)
	at com.sii.eucaptcha.security.JwtToken.decodeToken(JwtToken.java:49)
	at com.sii.eucaptcha.security.JwtToken.verifyToken(JwtToken.java:40)
	at com.sii.eucaptcha.controller.CaptchaController.reloadCaptchaImage(CaptchaController.java:97)
```

**Comment by YvesMeersmans** [comment]
@Eddy-Hoevenaers Can you please reply and look into to this one?

**Comment by Eddy-Hoevenaers** [comment]
Hi all, i am working on the solution and improving the logging. As the exceptions are not throwed every time i need to track the root cause. I will update asap

**Comment by BRU-EUSurvey** [comment]
Hi there, any news on that?
There might be a need to integrate v1.1.

**Comment by Eddy-Hoevenaers** [comment]
Do you call it directly to the backend or remotely? Remotely we still have a CORS issue on the reload and validate calls.

**Comment by clam2310** [comment]
We simply installed your application (war) in a Tomcat and tried your demo application. Integration into our own application is on hold until at least the demo page works.
